### ISSUE TITLE
Add the possibility to merge results into a single report for multi-module projects

### ISSUE THREAD

**Issue by galet** [stevesaliman/gradle-cobertura-plugin#10]

**Comment by rjsang** [comment]
The path to the source files in merged xml files is incorrect as it does not take account of the paths to the subprojects. E.g. if you have this structure:
    root
    \ projectA
        com.example.TestA
    \ projectB
        com.example.TestB

The paths to source in your merged xml are com/example/TestA and com/example/TestB instead of projectA/com/example/TestA and projectB/com/example/TestB

**Comment by shevek** [comment]
I'm using the recipe above, slightly simplified.

1) I have to add mavenCentral() repository to the root project despite it having no code in it.
2) Source linkages are broken in the overall report.
3) It's now trying to run tests in the root project, which has no code, and no test suite.

**Comment by dawogfather** [comment]
I was having same issue as @rjsang and hence tweaked the build by @syncsynchalt a little to be: 

```
def subCoberturaFiles = subprojects.collect { new File(it.projectDir, '/build/cobertura/cobertura.ser') }
def subCoberturaSrcs = subprojects.collect { new File(it.projectDir, '/src/main/groovy') }
cobertura {
    coverageFormats = [ 'xml', 'html' ]
    coverageSourceDirs = subCoberturaSrcs
    coverageMergeDatafiles = subCoberturaFiles
}
test.dependsOn(subprojects.test)
```
which appears to have fixed the report source linkage issues.

**Comment by rajeevnaikte** [comment]
I used above configuration mentioned, but the index.html doesn't have link to classes of all subprojects. It has links for only one subproject.
