### ISSUE TITLE
Add aux classpath

### ISSUE THREAD

**Issue by elsennov** [stevesaliman/gradle-cobertura-plugin#100]
Hi, i know that we could add aux classpath in this library. But, i still don't know what to be added.
I missed this class:
`java.lang.ClassNotFoundException: android.content.DialogInterface$OnClickListener`
What should be added in auxiliaryClasspath ?
Thank you :)

**Comment by stevesaliman** [comment]
Unfortunately, I've never done Android development so I'm not sure how the Android plugin sets up a project.  The plugin assumes that everything can be found in ```project.sourceSets.main```.  A quick glance at the android plugin docs seems to suggest taht that is what gets used to build a project, but if Android projects use something besides the ```main``` sourceSet, you'd need to add that to the auxiliary classpath.

Sorry I couldn't give a better answer.
