### ISSUE TITLE
Plugin is corrupting the classpath (Android)

### ISSUE THREAD

**Issue by dampcake** [stevesaliman/gradle-cobertura-plugin#101]
On Android there is some kind of classpath issue. I am having trouble narrowing it down but thought I would post my progress so far (maybe someone can help!). I think it has something to do with the aux classpath but I may be on the wrong track.

You can find the code to reproduce this here:
https://github.com/dampcake/gradle-cobertura-plugin-bug

Running `gradlew test` succeeds but `gradlew cobertura test` does not.

**Comment by stevesaliman** [comment]
Thanks for the fix.  I just released version 2.3.1 with your fix.

Out of curiousity, does ```gradlew cobertura test``` do something different than ```gradlew cobertura``` in an Android project?  The ```cobertura``` task was meant to run all test tasks and generate a report - a short cut for ```gradlew test coberturaReport```

**Comment by dampcake** [comment]
Looks like the way the initial implementation was done for Android it only runs the coverage on the debug build by default (or another single specified variant).

`./gradlew test` on android runs the tests on all variants (debug and release are the two most common but there can be as many as the user specifies). Most non-debug builds will have ProGuard run on them and I am not sure yet what the implications are of this with cobertura but I will take a look.

**Comment by stevesaliman** [comment]
Thanks for the clarification.  I haven't done Android development, so I'm not familiar with what runs.

I'm wondering if we should have ```CoberturaExtension.initAndroid()``` do something different so that the ```cobertura``` task runs the same tests as the ```test``` task.

**Comment by kageiit** [comment]
I like the simplicity of the fix, but something to keep in mind is that the unit test task names can change with android gradle plugin versions. May not be an immediate problem, but something to watch out for in the future. Maybe we can expose that through the extension as well when needed.
