### ISSUE TITLE
coverageIgnores is confusing

### ISSUE THREAD

**Issue by crazy4groovy** [stevesaliman/gradle-cobertura-plugin#106]
Hi, the description for [coverageIgnores](https://github.com/stevesaliman/gradle-cobertura-plugin/blob/master/usage.md#configuration):

```
An array of regular expressions representing patterns within the source code 
that should be ignored, such as logging statements. This applies to code within a 
source file not to files themselves. see coverageIncludes for file level inclusion.
```

make it sound like I can do this:

`coverageIgnores = [/.*log\.info.*$/]` // line of source code

when all the examples I find only show me this:

`coverageIgnores = ['org.slf4j.Logger.*']` //class

Does the description need to be updated? Or should I be able to ignore lines of code?

P.S. when I use either, I still get branch coverage errors. Can this be fixed, so that log lines truly get ignored?

**Comment by stevesaliman** [comment]
The coverageIgnores are just a pass through to Cobertura's ```--ignores``` option.  My description of what it does is simply a copy of Cobertura's own documentation.

I would expect that you could ignore individual logging statements, but to be honest, I've never tried it.  I have noticed that Cobertura doesn't always do what I expect with a regular expression.  Out of curiosity, what would happen if you used ```coverageIgnores = ['*.log.info.*]```?
