### ISSUE TITLE
NoClassDefFoundError when running Cobertura

### ISSUE THREAD

**Issue by tony19** [stevesaliman/gradle-cobertura-plugin#107]
I'm experiencing a similar issue as #75 with v2.3.1, but the `NoClassDefFoundError` occurs with my own classes instead of the third-party ones indicated in the other issue. These errors don't happen when I run the `test` task without the `gradle-cobertura-plugin`. I've also tried the workarounds indicated in #75 to no avail.

Here's a snippet of the output:
```shell
$ ./gradlew clean cobertura
...
:logback-android-classic:processTestResources
:logback-android-classic:testClasses
:logback-android-classic:test

ch.qos.logback.classic.android.AndroidManifestPropertiesUtilTest > dataDirKeyFound                                                                             FAILED
    java.lang.ExceptionInInitializerError at AndroidManifestPropertiesUtilTest.java:49
        Caused by: java.lang.NullPointerException at AndroidManifestPropertiesUtilTest.java:49

ch.qos.logback.classic.android.AndroidManifestPropertiesUtilTest > multipleAndroidKeysFound                                                                    FAILED
    java.lang.NoClassDefFoundError

ch.qos.logback.classic.android.AndroidManifestPropertiesUtilTest > versionNameKeyFound                                                                         FAILED
    java.lang.NoClassDefFoundError

ch.qos.logback.classic.android.AndroidManifestPropertiesUtilTest > extDirKeyFound                                                                              FAILED
    java.lang.NoClassDefFoundError

ch.qos.logback.classic.android.AndroidManifestPropertiesUtilTest > versionCodeKeyFound                                                                         FAILED
    java.lang.NoClassDefFoundError
...
```

```
------------------------------------------------------------
Gradle 2.12
------------------------------------------------------------

Build time:   2016-03-14 08:32:03 UTC
Build number: none
Revision:     b29fbb64ad6b068cb3f05f7e40dc670472129bc0

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
JVM:          1.8.0_74 (Oracle Corporation 25.74-b02)
OS:           Mac OS X 10.11.3 x86_64
```

The code is at: https://github.com/tony19/logback-android/tree/gradle-build (Cobertura is the last task in my effort to convert from Maven to Gradle, so please excuse the mess). Any help would be appreciated! Thanks

**Comment by stevesaliman** [comment]
I think the issue in your case is that you've provided your own implementation of the slf4j.  

When you run ```gradle test```, slf4j finds it, and all is well.

When you run ```gradle cobertura```, it finds 2 copies of it - one in the classes directory, and one in the instrumented classes directory.  My guess is that slf4j is getting confused, and preventing the tests from running properly.  

I think the trick here is to exclude the classes directory from the classpath when you are running cobertura, or maybe move the slf4j implementation to a separate sub-project.

Sorry I couldn't come up with something more concrete, but hopefully this points you in a good direction.

**Comment by tony19** [comment]
Hmm. That doesn't appear to be the problem. I just tried running cobertura on only `logback-core`, which does not contain the SLF4J implementation, and the error still occurs. Also, if that really were an issue, Cobertura probably wouldn't work with my project in Maven (but it does).

**Comment by tony19** [comment]
I ended up switching to Jacoco, which works well for me.

**Comment by tgsmith61591** [comment]
I'm experiencing this same NoClassDefFoundError in v2.3.1... any ideas other than switching to jacoco? I'm trying to use this plugin in conjunction with the coveralls-gradle plugin, but if there is no known fix here, I may have to switch as well.
