### ISSUE TITLE
cobertura.pom using groovyVersion property - causes problems in build.gradle if same name used

### ISSUE THREAD

**Issue by boardbloke** [stevesaliman/gradle-cobertura-plugin#112]
I have a build script that has the following:
`
buildscript {
    ext {
        springBootVersion = '1.3.5.RELEASE'
        groovyVersion = '2.4.6:indy'   
        spockVersion = "1.0-groovy-2.4"
        powermockVersion = "1.6.4"
    }
    repositories {
        mavenCentral()
        maven { url "https://repo.spring.io/snapshot" }
        maven { url "https://repo.spring.io/milestone" }
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
        classpath("net.saliman:gradle-cobertura-plugin:2.3.1")
    }
}
`

This fails in the build with the error: 
`Processing of [user]\.gradle\caches\modules-2\files-2.1\net.sourceforge.cobertura\cobertura\2.1.1\a8881b08de8eedb1f65f6422de777cdfc36ba22f\cobertura-2.1.1.pom failed:
    'dependencies.dependency.version' for org.codehaus.groovy:groovy-all:jar must not contain any of these characters \/:"<>|?* but found : in net.sourceforge.cobertura:cobertura:2.1.1`

The issues goes away if I call my local groovyVersion variable "localGroovyVersion"

Looks like the test scoped dependency on groovy-all that uses the maven property groovyVersion in the cobertura pom is interfering in some way.

**Comment by stevesaliman** [comment]
I didn't know that Gradle properties would be used in maven poms.  I guess it is a way to inherit from a parent build.  Good to know

I think the issue is that you can't put a classifier in the version tag of a pom.xml file.  If you need cobertura to use the version you're setting up, you'll have to exclude it as a transitive dependency of the plugin, and manually include it as a dependency of the buildScript.

**Comment by boardbloke** [comment]
Hi Steve,

Its not that I want to use the version of groovy in the buildscript.  Its that your choice of names for your maven properties will likely clash with names chosen by people in their buildscripts.

As a result they will be modifying the versions of the dependencies used by your plugin without realising it - causing the kinds of issues that like the one I have encountered.

I was suggesting that you change your pom to use version names that are like likely to clash - like coberturaGroovyVersion or something...


Cheers
N
________________________________________

**Comment by stevesaliman** [comment]
The pom in question, and the property in it, is not part of the Gradle plugin, it is part of Cobertura itself.  To fix it, the Cobertura folks will need to fix it on their end.

**Comment by boardbloke** [comment]
Fair point! :-)
