### ISSUE TITLE
Cobertura report, show extra files who are "Unable to locate"

### ISSUE THREAD

**Issue by jianleon** [stevesaliman/gradle-cobertura-plugin#114]
In my cobertura report, it show the list of packages with everything involved in the project, I found a package that shows two files, (R.java, BuildConfig). When I click the files, the report show a message like this one: "Unable to locate file directory/R.java. Have you specified the source directory?".

I look for that directory and the files, don't exist. 
Why cobertura generates a report with those files if they don't exist? I need to ignore them

**Comment by stevesaliman** [comment]
It is hard to know what is happening in your build without knowing more details, but if other classes in your project are in the reports, and R.java and BuildConfig are also in your project, then my hunch is that the problem lies somewhere in cobertura itself.
