### ISSUE TITLE
ClassNotFoundException for all classes from dependencies (in Java project)

### ISSUE THREAD

**Issue by ralfhergert** [stevesaliman/gradle-cobertura-plugin#116]
By design the idea of pre-setting the auxiliaryClasspath to the compiled classes and project's dependencies is absolutely fine. But anyway I do get ClassNotFoundExceptions while instrumenting for all classes, which are defined in dependencies of my project.

After redefining the auxiliaryClasspath in my build.gradle file to

```
cobertura {
    auxiliaryClasspath = project.sourceSets.main.output + project.sourceSets.main.compileClasspath
}
```

it did solve this issue.

Is there maybe something wrong in [https://github.com/stevesaliman/gradle-cobertura-plugin/blob/master/src/main/groovy/net/saliman/gradle/plugin/cobertura/CoberturaExtension.groovy#L499](url)? It looks like a "plus" is missing there.

**Comment by stevesaliman** [comment]
Good catch.  I've just released version 2.4.0 that adds the plus.  Going forward, you only need to use the ```auxiliaryClasspath``` option if you have something that you need to add to the defaults.
