### ISSUE TITLE
gradle assemble fails with "peer not authenticated" using oracle jdk 7

### ISSUE THREAD

**Issue by asarver** [stevesaliman/gradle-cobertura-plugin#123]
I'm using travis, and when I specify using oracle jdk 7, on the travis automatic `gradle assemble` command, it's failing with a 

```bash
* What went wrong:

Error resolving plugin [id: 'net.saliman.cobertura', version: '2.2.8']

> Could not GET 'https://plugins.gradle.org/api/gradle/2.2.1/plugin/use/net.saliman.cobertura/2.2.8'.

   > peer not authenticated
```
I've tried using different gradle versions and different cobertura version with no success.
When I do 
```bash
curl -X GET https://plugins.gradle.org/api/gradle/2.2.1/plugin/use/net.saliman.cobertura/2.2.8
```
I get back:
```bash
{
  "id" : "net.saliman.cobertura",
  "version" : "2.2.8",
  "implementation" : {
    "gav" : "net.saliman:gradle-cobertura-plugin:2.2.8",
    "repo" : "https://plugins.gradle.org/m2"
  },
  "implementationType" : "M2_JAR",
  "legacy" : true
}
```

When I change travis to use oracle jdk 8, `gradle assemble` retrieves the plug in fine. 

Also, if I do `gradle assemble` using the version of gradle I downloaded during the build, it works.

**Comment by stevesaliman** [comment]
I'm not sure what could be causing this.  I can't think of anything in the plugin itself that would cause a peer authentication issue.  I did a quick search on the issue, and saw several posts that talk about the Gradle version (one person had to go from 2.10 to 2.11), and the configuration of the repositories in the build script.

I haven't worked with Travis CI yet, so I'm not sure if it might be introducing issues of its own...

**Comment by kt3k** [comment]
We experienced a very similar issue in [our project](https://github.com/kt3k/coveralls-gradle-plugin) and it's fixed by [upgrading gradle wrapper version from 2.10 to 2.13](https://github.com/kt3k/coveralls-gradle-plugin/pull/74). (2.14 seems introducing another issue and doesn't work for our case.)

**Comment by stevesaliman** [comment]
The comment from @kt3k seems to confirm that this is a Gradle issue and not a plugin issue, so I am closing the plugin issue.
