### ISSUE TITLE
why can't I generate reports for multiple subprojects?

### ISSUE THREAD

**Issue by gtludwig** [stevesaliman/gradle-cobertura-plugin#127]
The project I'm working is structured as a root project with four subprojects.

I was able to generate the reports for all projects but they were stored in the build folder which is included on the .gitignore file, so not pushed to git.

Then I managed to configure the cobertura plugin so I create a separate directory on the root project's folder called reports, but this only generated the coverage report for the root project. There was no reports folder created on any of the subprojects.

I googled a bit and found some links here and there, but no decisive solution. For the moment I have the root project's build.gradle excerpt that covers cobertura:

```
plugins {
    id "org.sonarqube" version "2.2.1"
    id 'net.saliman.cobertura' version '2.4.0'
}

apply plugin: 'groovy'
apply plugin: 'cobertura'

cobertura {
    coverageFormats = ['html', 'xml']
    coverageReportDir = new File("$projectDir/reports/cobertura")
    rootProject.subprojects.each {
        coverageReportDir = new File("$it.name/reports/cobertura")
    }
}
```

On all projects, I have a cobertura.gradle file that looks like this:

```
logger.info "Configuring Cobertura Plugin"

configurations{
    coberturaRuntime {extendsFrom testRuntime}
}

dependencies {
    coberturaRuntime 'net.sourceforge.cobertura:cobertura:2.1.1'
}

def serFile="${project.buildDir}/cobertura.ser"
def classes="${project.buildDir}/classes/main"
def classesCopy="${classes}-copy"


task cobertura(type: Test){
    dependencies {
        testRuntime 'net.sourceforge.cobertura:cobertura:2.1.1'
    }

    systemProperties["net.sourceforge.cobertura.datafile"] = serFile
}

cobertura.doFirst  {
    logger.quiet "Instrumenting classes for Cobertura"
    ant {
        delete(file:serFile, failonerror:false)
        delete(dir: classesCopy, failonerror:false)
        copy(todir: classesCopy) { fileset(dir: classes) }

        taskdef(resource:'tasks.properties', classpath: configurations.coberturaRuntime.asPath)
        'cobertura-instrument'(datafile: serFile) {
            fileset(dir: classes,
                    includes:"**/*.class",
                    excludes:"**/*Test.class")
        }
    }
}

cobertura.doLast{
    if (new File(classesCopy).exists()) {
        ant.'cobertura-report'(destdir:"${project.reportsDir}/cobertura",
                format:'html', srcdir:"src/main/java", datafile: serFile)

        ant.delete(file: classes)
        ant.move(file: classesCopy, tofile: classes)
    }
}
```

How do I get it running?

**Comment by stevesaliman** [comment]
The following should do the trick:
```gradle
allprojects {
  apply plugin: 'groovy'
  apply plugin: 'cobertura'
  def rptDir = new File(it.projectDir, 'reports/cobertura')
  cobertura {
    coverageFormats = ['html', 'xml']
    coverageReportDir = rptDir
}
```

The key bit here is that ```it``` inside the cobertura block is an Extension.  You need the ```it``` of the allprojects block, which is a Project.

I'm not sure what the cobertura.doFirst and cobertura.doLast blocks are for - you shouldn't need them to get cobertura to run properly.

You may also want to add the report directories to your ```clean``` task if you want them to be cleaned up when running ```gradle clean```.
