### ISSUE TITLE
Problems generating too long filenames.

### ISSUE THREAD

**Issue by magmax** [stevesaliman/gradle-cobertura-plugin#130]
In our team, there are some people using tables with several parameters, which are long individually, so the filename generated to store the report is too long and the OS complains, ruining our Jenkins builds.

The problem, indeed, is in the XML final report generation, not in the build itself.

Maybe there should be a way to trunk the filename in order to avoid such a lame failure.

Thank you.

**Comment by stevesaliman** [comment]
The XML Reports are generated by Cobertura itself, not the gradle-cobertura-plugin.  The plugin is just a thin wrapper to the cobertura command line executor.

Problems with report generation would need to be fixed by the Cobertura team.  Your best bet is to report the issue there.
