### ISSUE TITLE
Build successful even when check failed

### ISSUE THREAD

**Issue by piotrgajow** [stevesaliman/gradle-cobertura-plugin#134]
During project check, cobertura reports `project failed coverage check`, however gradle still treats build as successful.

![cobertura](https://user-images.githubusercontent.com/3736869/27503002-b25ef8b4-5878-11e7-8454-d06502d909b4.PNG)

**Comment by stevesaliman** [comment]
By default, the Cobertura plugin only reports on the amount of coverage.  If you want to fail the build when the coverage is below a particular threshold, you need to set ```coverageCheckHaltOnFailure = true``` in your ```cobertura``` block.

The idea is that some users will want to fail the build when coverage is low, but others only want to know about it and proceed.  The coverageCheckHaltOnFailure property allows users to decide what behavior they want.
