### ISSUE TITLE
Cobertura generates a Gradle deprecation warning

### ISSUE THREAD

**Issue by stevendlander** [stevesaliman/gradle-cobertura-plugin#137]
Tested on: 2.3.1 and 2.4.0

What happens:  When this cobertura is an active plugin on a Gradle build, the following warning is shown:
```
Gradle now uses separate output directories for each JVM language, but this build assumes a single directory for all classes from a source set. This behaviour has been deprecated and is scheduled to be removed in Gradle 5.0
```

When cobertura is removed from the build.gradle of the project, this warning is no longer generated.  Debug log shows this warning is generated during the processTestResources task for cobertura.

**Comment by stevendlander** [comment]
Tested with Gradle version 4.1-bin

**Comment by stevesaliman** [comment]
Version 2.5.0 was released a couple of months ago to address this issue.  If you update your build to this version, the deprecation warning should go away.
