### ISSUE TITLE
coverageExcludes - for a fileName

### ISSUE THREAD

**Issue by rajademo** [stevesaliman/gradle-cobertura-plugin#140]
Need some help to excludes for Test Files recursively that ends with Test (xxxTest.class). Used the following regex  

> coverageExcludes

 = ['.&#10033;Test.[A-Z]&#10033;'] 

> 

 , but it is not working properly. 

Please check and let me know if i miss anything

**Comment by rajademo** [comment]
any updates. Thanks in advance

**Comment by stevesaliman** [comment]
I think the regex you need is simply `coverageExcludes=['.*Test']`

The regex you are using will only exclude files that have a character after the word Test, followed by one or more capital letters.

I don't remember if the plugin considers the extension or not, so if the above doesn't work, you could try `coverageExcludes=['.*Test.class']`
