### ISSUE TITLE
Error with new build:gradle 3.0.0

### ISSUE THREAD

**Issue by AlfonsoCase** [stevesaliman/gradle-cobertura-plugin#141]
Hello,
Recently I updated my project to the new build:gradle 3.0.0 and now I'm not able to open the cobertura report. This is the error that I receive:

```
> Configure project :CoreModule
Configuration 'provided' in project ':CoreModule' is deprecated. Use 'compileOnly' instead.

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':CoreModule:instrument'.
> Resolving configuration 'debugCompile' directly is not allowed 
```

I'm using gradle's new dependency configurations in all my Android modules: implementation, api, compileOnly, and runtimeOnly, but the problem persist.

Any help would be appreciated. Thanks in advance.

**Comment by Rackles** [comment]
We have the same problem in our project. As a result we can not update to build:gradle 3.0.0. .

It seems like that a possible fix already exists. Would it be possible to add a pull request for this fix. 

Any help would be appreciated. Thanks in advance.

**Comment by edu-gimenez** [comment]
I tried to create a PR with the necessary changes but it was not correct. https://github.com/stevesaliman/gradle-cobertura-plugin/pull/142
I have a project with:
* BaseLibrary,
* Library1, Library2, ..., LibraryN using BaseLibrary
* AppModule using Library1, ..., LibraryN

With the previous PR, BaseLibrary worked (`${androidVariant} CompileClasspath` contains the required classes), but not with Library1 ... N because `{androidVariant} CompileClasspath`  was empty. I was reviewing the properties of the gradle libraries and I didn't find any that had the necessary classpaht to use here:
https://github.com/edu-gimenez/gradle-cobertura-plugin/blob/66e6def9ecb95a014a44b2a66d3fa90d306c8513/src/main/groovy/net/saliman/gradle/plugin/cobertura/CoberturaExtension.groovy#L557

In my case in all my libraries I use dagger2 with `annotationProcessor` and I saw that in the property `${androidVariant} AnnotationProcessorClasspath` contains all the necessary classes for all libraries, so I modified my local gradle-coverage-plugin to read that property .

I know it's wrong but I do not have much knowledge about Gradle, so until there is a solution I have no other choice.
I hope it helps you

**Comment by Rackles** [comment]
Ah ok. I did not see the pull request you mentioned. 

Thanks for the fast response.

**Comment by wiomoc** [comment]
I've tested your changes and they work for me, I've also added support for kotlin
#144

**Comment by stevesaliman** [comment]
Version 2.5.2 of the plugin has been released to include #144 

Does this resolve the issues you're having?

**Comment by edu-gimenez** [comment]
@wiomoc @stevesaliman version 2.5.2 doesn't work for build:gradle:3.0.0 . I have a base library called CoreModule where everything works ok.

But in the LocationModule library that implements CoreModule when I launching cobertura, the following error appears:

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':LocationModule:instrument'.
> Could not resolve all task dependencies for configuration ':LocationModule:debugCompileClasspath'.
   > More than one variant of project :CoreModule matches the consumer attributes:
       - Configuration ':CoreModule:debugApiElements' variant android-aidl:
           - Found artifactType 'android-aidl' but wasn't required.
           - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
           - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
           - Found com.android.build.gradle.internal.dependency.VariantAttr 'debug' but wasn't required.
           - Required org.gradle.api.attributes.Usage 'java-api' and found compatible value 'java-api'.
       - Configuration ':CoreModule:debugApiElements' variant android-classes:
           - Found artifactType 'android-classes' but wasn't required.
           - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
           - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
           - Found com.android.build.gradle.internal.dependency.VariantAttr 'debug' but wasn't required.
           - Required org.gradle.api.attributes.Usage 'java-api' and found compatible value 'java-api'.
       - Configuration ':CoreModule:debugApiElements' variant android-manifest:
           - Found artifactType 'android-manifest' but wasn't required.
           - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
           - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
           - Found com.android.build.gradle.internal.dependency.VariantAttr 'debug' but wasn't required.
           - Required org.gradle.api.attributes.Usage 'java-api' and found compatible value 'java-api'.
       - Configuration ':CoreModule:debugApiElements' variant android-renderscript:
           - Found artifactType 'android-renderscript' but wasn't required.
           - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
           - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
           - Found com.android.build.gradle.internal.dependency.VariantAttr 'debug' but wasn't required.
           - Required org.gradle.api.attributes.Usage 'java-api' and found compatible value 'java-api'.
       - Configuration ':CoreModule:debugApiElements' variant jar:
           - Found artifactType 'jar' but wasn't required.
           - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
           - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
           - Found com.android.build.gradle.internal.dependency.VariantAttr 'debug' but wasn't required.
           - Required org.gradle.api.attributes.Usage 'java-api' and found compatible value 'java-api'.
```

#144 is based in #142. I closed my PR #142 myself because I detected this problem

**Comment by stevesaliman** [comment]
Unfortunately, I don't have experience with Android builds.

Maybe @wiomoc has some ideas?

**Comment by edu-gimenez** [comment]
It seems that with gradle3 it is not necessary to add any path automatically.
In #145 the plugin works with single appModule or with libraries. @wiomocm can you check it in your project too?

**Comment by wiomoc** [comment]
@edu-gimenez Your patch is even better and it works with my single module kotlin app with out a problem.

**Comment by stevesaliman** [comment]
I'm looking at merging #145 and I have a question, and there is code that talks about Gradle 3.0, but I don't think it is Gradle itself that is version 3 that we're dealing with is it?  I'm guessing that we're dealing with Android Tools version 3.  

I'd like to slightly clean up some of the method names after the merge to avoid confusion, but I need to make sure I'm not confused first :-)

**Comment by edu-gimenez** [comment]
Hi @stevesaliman , you are right. It is for AndroidToolsVersion 3, I'm sorry for the misunderstanding

**Comment by stevesaliman** [comment]
Version 2.5.3 has just been released with #145 included.  Does this fix the issue?

**Comment by stevesaliman** [comment]
Release 2.5.4 has just been released which fixes an issue we found with 2.5.3.  Does version 2.5.4 fix the issue?

**Comment by AlfonsoCase** [comment]
2.5.4 release works perfect. The issue can be closed.
Many thanks!

**Comment by stevesaliman** [comment]
I'm glad it's working now.  Thanks for the feedback.

**Comment by tray1990** [comment]
More than one variant of project :libraryLoadingIndicator matches the consumer attributes:
  - Configuration ':libraryLoadingIndicator:debugApiElements' variant android-aidl:
      - Found artifactType 'android-aidl' but wasn't required.
      - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
      - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
      - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
      - Required org.gradle.usage 'java-api' and found compatible value 'java-api'.
  - Configuration ':libraryLoadingIndicator:debugApiElements' variant android-classes:
      - Found artifactType 'android-classes' but wasn't required.
      - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
      - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
      - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
      - Required org.gradle.usage 'java-api' and found compatible value 'java-api'.
  - Configuration ':libraryLoadingIndicator:debugApiElements' variant android-manifest:
      - Found artifactType 'android-manifest' but wasn't required.
      - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
      - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
      - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
      - Required org.gradle.usage 'java-api' and found compatible value 'java-api'.
  - Configuration ':libraryLoadingIndicator:debugApiElements' variant android-renderscript:
      - Found artifactType 'android-renderscript' but wasn't required.
      - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
      - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
      - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
      - Required org.gradle.usage 'java-api' and found compatible value 'java-api'.
  - Configuration ':libraryLoadingIndicator:debugApiElements' variant jar:
      - Found artifactType 'jar' but wasn't required.
      - Required com.android.build.api.attributes.BuildTypeAttr 'debug' and found compatible value 'debug'.
      - Found com.android.build.api.attributes.VariantAttr 'debug' but wasn't required.
      - Required com.android.build.gradle.internal.dependency.AndroidTypeAttr 'Aar' and found compatible value 'Aar'.
      - Required org.gradle.usage 'java-api' and found compatible value 'java-api'.
