### ISSUE TITLE
Android Gradle 3.0 error

### ISSUE THREAD

**Issue by msbouchedid** [stevesaliman/gradle-cobertura-plugin#143]
Updated to Android Studio 3.0 along with Gradle 3.0 and tried to run the cobertura gradle task and got the following error: 

```
Error:Could not determine the dependencies of task ':app:instrument'.
> Resolving configuration 'debugCompile' directly is not allowed
```

Cobertura was working fine with the previous Android Studio & gradle version of 2.3.x

**Comment by msbouchedid** [comment]
Hello, it has been a couple days since anyone has answered... Can someone please help me out?

Thanks.

**Comment by wiomoc** [comment]
#144

**Comment by stevesaliman** [comment]
Thank you @wiomoc for the pull request.  Version 2.5.2 if the plugin has been released with your changes to support Android Tools 3.0.  

@msbouchedid Does this fix your issue?

**Comment by msbouchedid** [comment]
@wiomoc @stevesaliman I have confirmed that this works. Thank you guys so much for the update. Love the library!
