### ISSUE TITLE
Unable to Resolve cobertura plug-in in Ubuntu 18.04, works fine in Ubuntu 16.04

### ISSUE THREAD

**Issue by maazmmd** [stevesaliman/gradle-cobertura-plugin#154]
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve net.saliman:gradle-cobertura-plugin:2.2.5.

Required by:
         project :
      > Could not resolve net.saliman:gradle-cobertura-plugin:2.2.5.
         > Could not get resource 'https://repo.maven.apache.org/maven2/net/saliman/gradle-cobertura-plugin/2.2.5/gradle-cobertura-plugin-2.2.5.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/net/saliman/gradle-cobertura-plugin/2.2.5/gradle-cobertura-plugin-2.2.5.pom'.
               > java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
   > Could not resolve org.kt3k.gradle.plugin:coveralls-gradle-plugin:2.0.1x.
     Required by:
         project :
      > Could not resolve org.kt3k.gradle.plugin:coveralls-gradle-plugin:2.0.1x.
         > Could not get resource 'https://repo.maven.apache.org/maven2/org/kt3k/gradle/plugin/coveralls-gradle-plugin/2.0.1x/coveralls-gradle-plugin-2.0.1x.pom'.
            > Could not GET 'https://repo.maven.apache.org/maven2/org/kt3k/gradle/plugin/coveralls-gradle-plugin/2.0.1x/coveralls-gradle-plugin-2.0.1x.pom'.
               > java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

**Comment by maazmmd** [comment]
Unable to find any Solution. Kindly let me know where am I going wrong

**Comment by stevesaliman** [comment]
Sorry for the long delay...

This post on [Slashdot](https://askubuntu.com/questions/971059/17-10-openjdk-and-oracle-jdk-8-and-9-the-trustanchors-parameter-must-be-non-empt) talks about this problem.  It is an issue with the JDK, and the post has a solution for it.
