### ISSUE TITLE
Gradle 5.1 compabitility issues

### ISSUE THREAD

**Issue by rpalcolea** [stevesaliman/gradle-cobertura-plugin#156]
In gradle 5.1, `TaskContainer.java` is now decorated with CollectionCallbackActionDecorator -> https://github.com/gradle/gradle/commit/b40f10ac6e52ceeb8ab2b4a45acd8c72693a6ad7#diff-40a5a0b3f1d659c2d18f3684d17156a5

 
This commit also applies the change to plugins owned by Gradle that make use of `TaskReportContainer` (internal API).

 
The cobertura plugin requires a change in `CoberturaReportsImpl` to use the new `CollectionCallbackACtionDecorator` in https://github.com/stevesaliman/gradle-cobertura-plugin/blob/master/src/main/groovy/net/saliman/gradle/plugin/cobertura/CoberturaReportsImpl.java#L12

**Comment by stevesaliman** [comment]
The 2.6.0-SNAPSHOT release has been uploaded to Maven's snapshot repo.  You can get to it in your project by adding `maven { url "https://oss.sonatype.org/content/repositories/snapshots" }` to the `repositories` block inside your `buildscript` block.

Does this release work in a Gradle 5 project?  If so, I'll go ahead and do a production release.

**Comment by rpalcolea** [comment]
Hi! Yes it works with gradle 5

**Comment by stevesaliman** [comment]
I was able to publish the plugin to the Gradle plugin portal, but I cannot figure out how to get it to publish to Maven Central.  It seems that the new `java-gradle-plugin` and `maven-publish` plugins don't play nice with each other.  It keeps insisting on trying to publish to the wrong group on the Maven side.

**Comment by stevesaliman** [comment]
I think I've gotten if figured out.  Version 2.6.0 of the Cobertura plugin is now available in all the usual places.

Thank you for your help getting the plugin working in Gradle 5.

**Comment by rpalcolea** [comment]
Awesome! Thank you @stevesaliman
