### ISSUE TITLE
Gradle 6.x support

### ISSUE THREAD

**Issue by rpalcolea** [stevesaliman/gradle-cobertura-plugin#165]
`CoberturaReportsImpl` uses internal API that isn't present in Gradle 6.x anymore

https://github.com/stevesaliman/gradle-cobertura-plugin/pull/164/files fixes this

**Comment by mecorusfc** [comment]
Due to vulnerabilities found in Gradle 5, we are now forced to upgrade to 6 but Cobertura won't work in 6.  Here is the error:
* What went wrong:
An exception occurred applying plugin request [id: 'net.saliman.cobertura', version: '2.6.1']
> Failed to apply plugin [id 'net.saliman.cobertura']
   > Could not create task ':generateCoberturaReport'.
      > Could not create task of type 'GenerateReportTask'.
         > Could not create an instance of type net.saliman.gradle.plugin.cobertura.CoberturaReportsImpl.
            > org.gradle.api.reporting.internal.TaskReportContainer.<init>(Ljava/lang/Class;Lorg/gradle/api/Task;)V

I see a pull request.  Any hope of getting that done soon?  Thanks Mike

**Comment by stevesaliman** [comment]
I'll look into this as soon as I get some time.

I don't see anything about a Gradle 6.x release, though.  Do you mean Gradle 5.6?

**Comment by mecorusfc** [comment]
The OWASP Dep Check vulnerability in Gradle 5.6.1 and 5.6.2 requires Gradle 6.0 to fix.  Right now, only Gradle 6.0-rc1 is available.  You have a PR ready to merge to give your plugin 6.0 capability.  That’s what I’m asking for.

#164: https://github.com/stevesaliman/gradle-cobertura-plugin/pull/164

Thanks,

Michael Corum
VP, Technical Architecture Solutions

RGA Reinsurance Company
16600 Swingley Ridge Road
Chesterfield, Missouri 6301701706
T 636.736.7066
www.rgare.com

**Comment by stevesaliman** [comment]
The Gradle 6.0 release candidate wasn't available when this issue was first reported, and I didn't see it on any roadmaps at that time either, so this just didn't seem like a very high priority - especially since it was a breaking change.  It seemed more like a future proofing kind of thing.  They've only just last week released a 6.0 release candidate.

There has also been some chatter in recent weeks of a Cobertura release to solve some long standing issues with it, and I've been waiting to see if that was going to materialize.

I understand that there is a pull request ready to go that could be easily merged, but you also mentioned OWASP, so I suspect that security is important to you.  Now what kind of developer would I be if I just merged pull requests without vetting the code first? :smiley: 

Steve

**Comment by eyalroth** [comment]
@stevesaliman I don't know how long it'll take for Gradle 6 to officially get released, but it does include some major improvements which may encourage people to upgrade. One of the more noteworthy improvements for me is the update to Scala's compilation (via zinc).

**Comment by rpalcolea** [comment]
agree with @eyalroth , also I think we as plugin authors should be more proactive on supporting new versions as soon as RCs come out so people can upgrade right away

**Comment by mecorusfc** [comment]
Is your plan to wait for the Cobertura release?  I ask because as 6.0 candidates come out, I have to report back to the Gradle team that I can’t test until we can get working plugins (yours isn’t the only one but it is the most important for my work).  Thoughts?

Michael Corum
VP, Technical Architecture Solutions

RGA Reinsurance Company
16600 Swingley Ridge Road
Chesterfield, Missouri 6301701706
T 636.736.7066
www.rgare.com

**Comment by stevesaliman** [comment]
I'm not planning on waiting for an official release.  I just need some free time, which has been frustratingly hard to get lately due to other commitments.  I'll try to take a look at it this weekend, but next weekend is looking more likely.

I apologize for the inconvenience,

Steve

**Comment by stevesaliman** [comment]
I found some time this weekend, and was able to release version 3.0.0 of the plugin, which supports Gradle 6.  This is a breaking release for really old JVMs and Gradles; the plugin now only works with Java 8+ and Gradle 5.1+, but I doubt that will cause anyone any issues.

Thank you all for your patience while I got this release out.

**Comment by mecorusfc** [comment]
I switched to 3.0.0 and Gradle 6.0 and tried to run the wrapper and got this:

An exception occurred applying plugin request [id: 'net.saliman.cobertura', version: '3.0.0']
> Failed to apply plugin [id 'net.saliman.cobertura']
   > Could not create task of type 'GenerateReportTask'.

I think this is the same error I was getting before.  Are other changes needed to my build.gradle?

Michael Corum
VP, Technical Architecture Solutions

RGA Reinsurance Company
16600 Swingley Ridge Road
Chesterfield, Missouri 6301701706
T 636.736.7066
www.rgare.com

**Comment by mecorusfc** [comment]
Maybe I’m too early.  I can’t find 3.0.0 on mvnrepository yet so maybe it isn’t published.  Thanks for merging the PR.  Let us know when it is published.

Thanks,

Michael Corum
VP, Technical Architecture Solutions

RGA Reinsurance Company
16600 Swingley Ridge Road
Chesterfield, Missouri 6301701706
T 636.736.7066
www.rgare.com



From: "Corum, Michael" <mcorum@rgare.com>
Date: Sunday, November 10, 2019 at 6:12 PM
To: stevesaliman/gradle-cobertura-plugin <reply@reply.github.com>, stevesaliman/gradle-cobertura-plugin <gradle-cobertura-plugin@noreply.github.com>
Cc: Comment <comment@noreply.github.com>
Subject: Re: [stevesaliman/gradle-cobertura-plugin] Gradle 6.x support (#165)

I switched to 3.0.0 and Gradle 6.0 and tried to run the wrapper and got this:

An exception occurred applying plugin request [id: 'net.saliman.cobertura', version: '3.0.0']
> Failed to apply plugin [id 'net.saliman.cobertura']
   > Could not create task of type 'GenerateReportTask'.

I think this is the same error I was getting before.  Are other changes needed to my build.gradle?

Michael Corum
VP, Technical Architecture Solutions

RGA Reinsurance Company
16600 Swingley Ridge Road
Chesterfield, Missouri 6301701706
T 636.736.7066
www.rgare.com

**Comment by stevesaliman** [comment]
Strange - It should have been there.  Sometimes it takes a couple of hours to propagate.  It is there now, and I just checked it against one of my projects using Gradle 6 and the 3.0.0 version of the plugin.  It worked as I expected on my end.

**Comment by mecorusfc** [comment]
Same error this morning and it’s still not on mvnrepository.  Can you verify that I’m hitting the right page in mvnrepository?

https://mvnrepository.com/artifact/net.saliman/gradle-cobertura-plugin

id 'net.saliman.cobertura' version '3.0.0'

Is there a different page or dependency coordinate I should try?

Michael Corum
VP, Technical Architecture Solutions

RGA Reinsurance Company
16600 Swingley Ridge Road
Chesterfield, Missouri 6301701706
T 636.736.7066
www.rgare.com

**Comment by stevesaliman** [comment]
I'm not sure how mvnreporsitory.com populates, but I can see the 3.0.0 version of the plugin on [Maven Central](https://search.maven.org/artifact/net.saliman/gradle-cobertura-plugin/3.0.0/jar), and Gradle's own [Plugin Repository](https://plugins.gradle.org/plugin/net.saliman.cobertura).  I also pushed it to Bintray (which is supposed to feed jcenter), but that may be our outlier.  Bintray sees the right version of the plugin [here](https://bintray.com/stevesaliman/maven/gradle-cobertura-plugin), but it may not have pushed yet.

For grins, if you change the version of the plugin to something invalid (like 3.1.0), do you get the same error, or a different one?  That will at least tell us if the plugin is found but not working, or not found.

**Comment by mecorusfc** [comment]
Thanks, I figured it out.  It’s working now.  I had to delete all my caches as it seemed to be insisting on bring in old versions.

Michael Corum
VP, Technical Architecture Solutions

RGA Reinsurance Company
16600 Swingley Ridge Road
Chesterfield, Missouri 6301701706
T 636.736.7066
www.rgare.com

**Comment by stevesaliman** [comment]
I'm glad to hear that it is working now.  Clearing caches is a good tip for anyone who finds this issue later.

Steve
