### ISSUE TITLE
Support for Kotlin?

### ISSUE THREAD

**Issue by jferrater** [stevesaliman/gradle-cobertura-plugin#174]
Hi,

We are testing this plugin as a coverage tool in our Kotlin project. I noticed that the default coverage directories only mentioned Java, Groovy and Scala directories.  The coverage report was generated but not entirely sure if the coverage data were reliable. Does this also work with Kotlin? Kotlin may be different as it generates quite a lot of bytecode.

Best regards,
Joffry

**Comment by stevesaliman** [comment]
The gradle cobertura plugin should just be a wrapper around cobertura itself, so if cobertura supports Kotlin, the plugin should work with it as well.  The larger issue is whether or not cobertura itself will work, though given how long it has been since cobertura was last released.
