### ISSUE TITLE
Cobertura Gradle Powermock Issue

### ISSUE THREAD

**Issue by lpambagoda** [stevesaliman/gradle-cobertura-plugin#40]
Hi,

When we use power mock with gradle, gradle-cobetura-plugin does not generate the coverage report for the tests with power mock. However tests with out power mock is shown in the coverage report properly even-though they are in the same project. 

Please check the following sample code I have written to recreate the issue.

https://github.com/lpambagoda/cobertura-gradle-powermock-issue

I have tested this with gradle 1.7 to 1.10 with  gradle-cobetura-plugin 2.2.2. 

There was a similar issue reported for maven as well. However that issue is fixed now.

http://www.jsfblog.info/2010/02/cobertura-code-coverage-with-maven-and-powermock/

Best Regards
Lasantha

**Comment by stevesaliman** [comment]
Quite a few things have been updated since this issue was first opened.  Is this still an issue with Gradle 2 and the latest versions of Cobertura and this plugin?

**Comment by Ninja91** [comment]
Yes. I am also facing issues with coverage. I am working on an android app and using PowerMockRunner for unit testing. Wherever, I am using mocking using either Mockito or PowerMockito, the coverage is 0. 
Did anyone come up with a solution for this?

**Comment by lpambagoda** [comment]
Hello,

I had some time to look in to the issue again. This was happening since I have not extended my test case from PowerMockTestCase. 

You can see the exact fix I did for the test case from following link.
https://github.com/lpambagoda/cobertura-gradle-powermock-issue/commit/7335e1847d74c32ceb269c30622a224a32282589

So we can mark this as fixed.

Cheers
Lasantha

**Comment by crazy4groovy** [comment]
Hi, I just ran into this issue as well. I'm getting something like:

`com.foo.PermissionManager failed coverage check. Line coverage rate of 0.0% is below 70.0%`

when that's clearly not the case (a println appears from inside PermissionManager method).

My dependencies are just like: [http://lpambagoda/cobertura-gradle-powermock-issue@7335e18](http://lpambagoda/cobertura-gradle-powermock-issue@7335e18)

```groovy
plugins {
    id 'groovy'
    . . .
    id 'net.saliman.cobertura' version '2.3.0' //https://github.com/stevesaliman/gradle-cobertura-plugin/blob/master/usage.md 
    // note that 2.2.2 won't download, only the latest will
}

dependencies {
    . . .
    testCompile 'org.spockframework:spock-core:1.0-groovy-2.4'
    testCompile 'org.mockito:mockito-all:1.10.19'
    testCompile "org.powermock:powermock-api-mockito:$powerMockVersion"
    testCompile "org.powermock:powermock-module-junit4:$powerMockVersion"
    testCompile "org.powermock:powermock-module-junit4-rule:$powerMockVersion"
    testCompile "org.powermock:powermock-classloading-xstream:$powerMockVersion"
}

Any thoughts? Could maybe `Spock` be causing the errors? Seems unlikely..

**Comment by stevesaliman** [comment]
I never was able to find the root cause of the issue.  I did notice that lpambagoda's problem was because his test cases didn't extend the right base class.  Could this be happening in your case?

**Comment by boardbloke** [comment]
I am having this problem as well.  I am using Gradle, Spock, PowerMock and Cobertura.

Spock requires that tests extend Specification, so they can't extend PowerMock's PowerMockTestCase.  So lpambagoda's solution does not work.

The issue I think is that PowerMock has a custom classloader that is being used to do the necessary modifications to allow static method mocking.

**Comment by boardbloke** [comment]
I found this, which I think is relevant.
https://www.jayway.com/2011/05/19/powermock-for-integration-testing/

**Comment by boardbloke** [comment]
I think this may be a cobertura issue, rather than anthing else.  I followed the above to force PowerMock to delegate classloading for sensitive clases to the parent classloader, and then got another issue - with cobertura this time.  Cobertura is failing to instrument the class containing the statics:

'java.lang.NoSuchMethodException: spockpoc.simple.GroovyClassContainingStatic.__c
obertura_classmap(net.sourceforge.cobertura.coveragedata.LightClassmapListener)
        at java.lang.Class.getDeclaredMethod(Class.java:2130)
        at net.sourceforge.cobertura.coveragedata.TouchCollector.applyTouchesToS
ingleClassOnProjectData(TouchCollector.java:127)
        at net.sourceforge.cobertura.coveragedata.TouchCollector.applyTouchesOnP
rojectData(TouchCollector.java:110)
        at net.sourceforge.cobertura.coveragedata.ProjectData.saveGlobalProjectD
ata(ProjectData.java:272)
        at net.sourceforge.cobertura.coveragedata.SaveTimer.run(SaveTimer.java:3
3)
        at java.lang.Thread.run(Thread.java:745)
[INFO] Cobertura: Loaded information on 6 classes.
[ERROR] Cannot apply touches
java.lang.NoSuchMethodException: spockpoc.simple.JavaClassCallingGroovyStatic.__
cobertura_classmap(net.sourceforge.cobertura.coveragedata.LightClassmapListener)

        at java.lang.Class.getDeclaredMethod(Class.java:2130)
        at net.sourceforge.cobertura.coveragedata.TouchCollector.applyTouchesToS
ingleClassOnProjectData(TouchCollector.java:127)
        at net.sourceforge.cobertura.coveragedata.TouchCollector.applyTouchesOnP
rojectData(TouchCollector.java:110)
        at net.sourceforge.cobertura.coveragedata.ProjectData.saveGlobalProjectD
ata(ProjectData.java:272)
        at net.sourceforge.cobertura.coveragedata.SaveTimer.run(SaveTimer.java:3
3)
        at java.lang.Thread.run(Thread.java:745)'
