### ISSUE TITLE
Cobertura depends on OLD xalan/xerces, breaks XInclude etc in apps

### ISSUE THREAD

**Issue by shevek** [stevesaliman/gradle-cobertura-plugin#41]
See https://github.com/cobertura/cobertura/issues/122

    configurations {
        cobertura.exclude group: 'xalan' 
        cobertura.exclude group: 'xerces'
    }

**Comment by stevesaliman** [comment]
I just released version 2.2.7  of the plugin, which uses updated libraries.  Is this still an issue?

**Comment by stevesaliman** [comment]
I'll assume that the latest version of the plugin, and its updated dependencies fixed this issue.  Feel free to re-open it if this is not the case.
