### ISSUE TITLE
Cobertura and gradle-cobertura-plugin dont work with gradle 2.0 and java 8

### ISSUE THREAD

**Issue by ejosiah** [stevesaliman/gradle-cobertura-plugin#56]
I've working on a project using gradle 2.0 and java8. The current gradle-cobertur-plugin does not work with gradle 2.0 as its using alot of gradle methods deprecated as of gradle-1.12 and removed in gradle-2.0.

I switched to gradle 1.8 but Cobertura is unable to cover the unit tests as its failing due to instrumentation errors I'm guessing -> java.lang.VerifyError: Expecting a stackmap frame at branch target 185.

**Comment by stevesaliman** [comment]
I just released version 2.2.7 of the plugin which uses version 2.1.1 of Cobertura, which in turn updates some of the other libraries used - especially ASM.  Is this still a problem in version 2.2.7?

**Comment by stevesaliman** [comment]
It looks like the culprit was slf4j.  See the fix for the referenced issue #75, it's solution seems to do the trick.

**Comment by peterlitvak** [comment]
I'm running Gradle 2.3 with cobertura plugin 2.2.8 under 1.8.0u40 JDK and applied suggestions from this issue as well as the #75 mentioned here.
I'm still getting java.lang.VerifyError: Expecting a stackmap frame at branch target 53
Any suggestions? Thanks

**Comment by tomaszezula** [comment]
I don't think this was every entirely resolved. I'm running Gradle 2.7 on 1.8.0u_51 JDK using Steve Saliman's Cobertura plugin (2.2.7) + enforced ASM dependency (5.0.3). Cobertura still won't understand lambdas. I switched to Jacoco, works like a charm.
