### ISSUE TITLE
coberturaCheck & coberturaReport behaviour inconsistent

### ISSUE THREAD

**Issue by mdjnewman** [stevesaliman/gradle-cobertura-plugin#63]
When I run `gradlew coberturaReport test` I get the correct coverage statistics, but when I run `gradlew coberturaCheck test` I consistently see 0% coverage on all classes.

Given the documentation saying "The ``coberturaCheck`` task does all the things ``coberturaReport`` does, but adds a test coverage check to the build.", I'm guessing this is not expected behaviour.

Has anyone else encountered this? Currently there doesn't seem to be a reliable way to fail the build if coverage is low. Let me know if more info is required.

**Versions:**
net.saliman:gradle-cobertura-plugin:2.2.5, gradlew --version output as below:

    Gradle 2.2

    Build time:   2014-11-10 13:31:44 UTC
    Build number: none
    Revision:     aab8521f1fd9a3484cac18123a72bcfdeb7006ec

    Groovy:       2.3.6
    Ant:          Apache Ant(TM) version 1.9.3 compiled on December 23 2013
    JVM:          1.7.0_71 (Oracle Corporation 24.71-b01)
    OS:           Windows 7 6.1 amd64

**Comment by HNygard** [comment]
Also had a problem with coberturaCheck. Found the dependency change in commit 3b6ce9c301ddc8f98b932e678c7b8c8079624760 and added the following to my build.gradle to fix the problem:

    coberturaCheck.dependsOn 'coberturaReport'

**Comment by davidmichaelkarr** [comment]
Isn't this issue fixed?

**Comment by HNygard** [comment]
@davidmichaelkarr: Fixed but not released

https://github.com/stevesaliman/gradle-cobertura-plugin/compare/Release_2.2.5...master

**Comment by stevesaliman** [comment]
I wanted to time my next release with the release of Cobertura 2.1, which seems to behave better with Java 8.  I keep hoping against hope that this will happen soon, although cobertura's release has been scheduled "Real soon now" for almost a year...

I released version 2.2.6 this morning.  It should be showing up in the normal locations in a couple of hours.
