### ISSUE TITLE
When running with --dry-run command line, the plugin complains about a missing coverage data file

### ISSUE THREAD

**Issue by maddingo** [stevesaliman/gradle-cobertura-plugin#64]
Because --dry-run doesn't actually run the instrumentation the coverage data file is not created. 
When running with --dry-run, the CoberturaRunner should not actually run cobertura but quietly return. 
I provided a pull request (#66) that addresses this issue.

**Comment by stevesaliman** [comment]
This has been fixed in release 2.2.6, which was released this morning.
