### ISSUE TITLE
coberturaCheck always fails for coberturaVersion 2.1.0-SNAPSHOT

### ISSUE THREAD

**Issue by owahlen** [stevesaliman/gradle-cobertura-plugin#70]
**Error Description**
I need cobertura 2.1.0-SNAPSHOT for Java 8 support. In our project we have coverage levels set to 50% and the CI server shall fail if these coverage levels are not met. Unfortunately the coverageCheck *always* fails even though all coverage levels seem to be met.

**Error Analysis**
By looking at the plugin code in CoberturaRunner:163 the call to *executeCobertura* is different for cobertura versions greater than 2.1.0. More specifically the third parameter in this line indicates to not use the SecurityManager.
This in turn _always_ leads to the exitStatus of -1 in CoberturaRunner:237.
And this in turn makes the coverage checks always fail in PerformCoverageCheckTask:35.

**Possible Solution**
I do not know if the Security Manager is switched off for a specific reason. If not then the third parameter in CoberturaRunner:237 should be _true_ instead of _false_. On the other hand I think it does not make much sense to always return an error code if the security manager is switched of!?

**Comment by owahlen** [comment]
see https://github.com/stevesaliman/gradle-cobertura-plugin/pull/71

**Comment by raniejade** [comment]
when will #71 be released? Can't upgrade to cobertura-2.1.1 because of this.

**Comment by stevesaliman** [comment]
I've just released version 2.2.7 of the plugin which uses Cobertura 2.1.1 by default, and includes the fix from Pull request #71. It should be showing up on Maven Central and the Gradle Plugin Page in the next few hours.

**Comment by stevesaliman** [comment]
Turns out the argument difference was intentional.

The security manager blocks acces to Cobertura 2.0.3's ```System.exit``` call, and lets us get at the intended return value.

Starting with 2.1.0, the coverage check no longer uses System.exit, so we no longer need the security manager.  Ther real issue is that we force failure when no exception happens, which I'll fix in the next version.

**Comment by stevesaliman** [comment]
I've just uploaded version 2.2.8-SNAPSHOT of the plugin to the Maven snapshot repository.  Do your projects still work correctly with the new version?  I want to make sure that the fix for Issue #74 doesn't break this one again.

**Comment by owahlen** [comment]
We have just tested 2.2.8-SNAPSHOT and it seems to work.

**Comment by stevesaliman** [comment]
Released 2.2.8.
