### ISSUE TITLE
Cobertura 2.1.1 released

### ISSUE THREAD

**Issue by samrocketman** [stevesaliman/gradle-cobertura-plugin#72]
How do I let my gradle cobertura file use the latest Cobertura?  I'd like to test cobertura/cobertura#184

**Comment by stevesaliman** [comment]
Thank you for letting me know that 2.1.1 was released.  I've been waiting for a 2.1 release for a while, and I missed the announcement.  I'll be updating the plugin in the next couple of days to use 2.1.1 by default, but until then, you can put ```coberturaVersion = '2.1.1'``` in the cobertura block of your build.gradle to tell the plugin to use the later version.

**Comment by samrocketman** [comment]
Thanks for the workaround in the meantime :).

**Comment by samrocketman** [comment]
I'll close this since you're now aware of it.  Speedy and good feedback @stevesaliman.
