### ISSUE TITLE
performCoverageCheck fails to fail the build with Cobertura 2.1.1

### ISSUE THREAD

**Issue by aszili** [stevesaliman/gradle-cobertura-plugin#74]
Using Cobertura version 2.0.3 with version 2.2.7 of the gradle-cobertura-plugin fails my build just fine if I set a high enough coverage target. Only changing the version of Cobertura to 2.1.1 makes the build pass. The fact that the coverage target is output by Cobertura but I suspect its exit code is now 0 even in this case, making the plugin believe the target is met.

**Comment by stevesaliman** [comment]
Good catch.  It looks like my attempt at fixing Issue #70 had soem unintended consequences.

I've just uploaded 2.2.8-SNAPAHOT to the Maven snapshot repository.  Does it fix your issue?

**Comment by aszili** [comment]
I tried the new version with Cobertura 2.1.1 and it worked, as in if I set a sufficiently high coverage target the build failed with the expected message.
