### ISSUE TITLE
Plugin has DEBUG log level ON by default for report generation

### ISSUE THREAD

**Issue by peterlitvak** [stevesaliman/gradle-cobertura-plugin#80]
```
[Thread-4] DEBUG n.s.c.coveragedata.TouchCollector - =================== START OF REPORT ========================
...
...
...
[Thread-4] DEBUG n.s.c.coveragedata.TouchCollector - ===================  END OF REPORT  ========================
```
Is there a way to change it via some property without introduction of any logger configs?

**Comment by stevesaliman** [comment]
I'm sorry, I'm not sure where you are seeing this.  When I run a build of the testclient, I don't see anything like this in my Gradle ouput, or in my reports.  Can you give me more information on your setup and the steps you are taking?

**Comment by peterlitvak** [comment]
The problem was that the cobertura was picking up the looging config from one of the integration test's logback.xml files in our project where the root level was set to DEBUG.
