### ISSUE TITLE
net.sourceforge.cobertura.javancss.parser.ParseException: Encountered " ">" "> ""

### ISSUE THREAD

**Issue by jfbibeau** [stevesaliman/gradle-cobertura-plugin#85]
There still seems to be some issues remaining with Java 8 lambdas.

I'm using `gradle-cobertura-plugin:2.2.8` and getting the following error:

```
Cobertura 2.1.1 - GNU GPL License (NO WARRANTY) - See COPYRIGHT file
net.sourceforge.cobertura.javancss.parser.ParseException: Encountered " ">" "> "" at line 268, column 88.
Was expecting one of:
    "assert" ...
    "boolean" ...
    "byte" ...
    "char" ...
    "double" ...
    "enum" ...
    "false" ...
    "float" ...
    "int" ...
    "long" ...
    "new" ...
    "null" ...
    "short" ...
    "super" ...
    "this" ...
    "true" ...
    "void" ...
    <INTEGER_LITERAL> ...
    <FLOATING_POINT_LITERAL> ...
    <CHARACTER_LITERAL> ...
    <STRING_LITERAL> ...
    <IDENTIFIER> ...
    "(" ...
    "!" ...
    "~" ...
    "++" ...
    "--" ...
    "+" ...
    "-" ...
    
	at net.sourceforge.cobertura.javancss.parser.JavaParser.generateParseException(JavaParser.java:10490)
```

Any ideas where I can start troubleshooting this? The line referenced in my code is a Java 8 lambda which Cobertura doesn't seem to be able to parse... 

Thanks!

**Comment by jfbibeau** [comment]
Taking a quick look, could it be this issue on the cobertura side? https://github.com/cobertura/cobertura/issues/176#issuecomment-114766252

**Comment by stevesaliman** [comment]
I think this is the issue you found on the Cobertura side.  The plugin is meant to be little more than a wrapper around Cobertura itself, and Cobertura does seem to have some issues with the new features of Java 8.
