### ISSUE TITLE
Excluding $ classes from cobertura report

### ISSUE THREAD

**Issue by andreshash** [stevesaliman/gradle-cobertura-plugin#87]
hello,  I am using a gradle-cobertura plugin for generating test coverage report, Now I am trying to exclude  the magic class from the coverage report.
for example: the class Notification have many magic class in coverage report
Notification	
Notification$1	
Notification$1$1	
Notification$1$2	
Notification$2
Notification$2$1	
Notification$2$2	
Notification$2$3	
Notification$2$4	
Notification$3	
Notification$3$1	
Notification$3$2	
Notification$3$3	
Notification$3$4	
Notification$4	
Notification$4$1	
Notification$5	
Notification$5$1

I have tried to customize the behavior of the Cobertura plugin by using a closure to configure the convention properties as below:

cobertura {
    coverageSourceDirs = sourcesSets.main.groovy.srcDirs
    coverageExcludes = ['.*\$\\d.class.*']
}

But the coverage report still showing the classes that I have excluded. Any help will be appreciated.

**Comment by stevesaliman** [comment]
The includes and excludes are looking for regular expressions.  Have you tried ```coverageExcludes = ['.*\$.*']``` in your configuration?

This should exclude any class with a '$' in the name.

**Comment by andreshash** [comment]
thanks
