### ISSUE TITLE
coberturaReport Not generating the report

### ISSUE THREAD

**Issue by 155martinmoreno** [stevesaliman/gradle-cobertura-plugin#97]
I'm using 
```
./gradlew clean assembleDebug coberturaReport
```
and the build folder does not contain any report... however using the 
```
cobertura
```
command instead does generate them.

am I doing something wrong?

**Comment by stevesaliman** [comment]
My guess is that no tests are actually being run.

The ```cobertura``` task causes all tasks of type ```Test``` to be executed as part of the build.  the idea is to be able to run all the tests in a project and generate a coverage report with one task.

The ```coberturaReport``` will make sure that a report is generated if any tests are run, but doesn't actually cause tests to run.  The idea here is that if you have a couple of test tasks, you can decide what tests should run, then have a report generated at the end.

I'm not an Android developer, but my guess is that ```assembleDebug``` builds things, but doesn't test anything.  You probably need to add one or more test tasks you your ```gradlew``` command.  ```gradlew clean assembleDebug test cobertura``` should run everything.

**Comment by 155martinmoreno** [comment]
You're right, no test is being run. I didn't realize they should run but now that I think about it,  it's totally logical.
Thanks
